package com.flutterforge.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.*;

@Slf4j
@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
public class ProxyController {

    private final WebClient webClient;
    private final ObjectMapper objectMapper;

    // ─────────────────────────────────────────────────────────
    // POST /api/proxy/test — fires a real API call on behalf of
    // the IDE (avoids CORS issues in the Electron renderer)
    // ─────────────────────────────────────────────────────────

    @PostMapping("/proxy/test")
    public Mono<Map<String,Object>> testEndpoint(@RequestBody TestRequest request) {
        log.info("Proxy test: {} {}", request.method(), request.url());

        WebClient.RequestHeadersSpec<?> spec;
        try {
            spec = switch (request.method().toUpperCase()) {
                case "POST", "PUT", "PATCH" -> webClient.method(
                    org.springframework.http.HttpMethod.valueOf(request.method().toUpperCase()))
                    .uri(request.url())
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(request.body() != null ? request.body() : "{}");
                default -> webClient.get().uri(request.url());
            };

            // Add mock headers if any param has location=header
            if (request.params() != null) {
                for (var p : request.params()) {
                    if ("header".equals(p.get("location")) && p.get("mockValue") != null) {
                        final String name = String.valueOf(p.get("name"));
                        final String val  = String.valueOf(p.get("mockValue"));
                        spec = spec.header(name, val);
                    }
                }
            }

            return spec.exchangeToMono(res -> res.bodyToMono(String.class)
                .map(body -> {
                    Map<String,Object> result = new LinkedHashMap<>();
                    result.put("status", res.statusCode().value());
                    // Try to pretty-print as JSON
                    try {
                        Object parsed = objectMapper.readValue(body, Object.class);
                        result.put("body", objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(parsed));
                    } catch (Exception e) {
                        result.put("body", body);
                    }
                    return result;
                })
            ).onErrorResume(e -> {
                Map<String,Object> err = new LinkedHashMap<>();
                err.put("status", 0);
                err.put("body", "Connection error: " + e.getMessage());
                return Mono.just(err);
            });

        } catch (Exception e) {
            Map<String,Object> err = new LinkedHashMap<>();
            err.put("status", 0);
            err.put("body", "Error: " + e.getMessage());
            return Mono.just(err);
        }
    }

    // ─────────────────────────────────────────────────────────
    // POST /api/generate/dart-models
    // Generates Dart model classes from Data File schemas
    // ─────────────────────────────────────────────────────────

    @PostMapping("/generate/dart-models")
    public Map<String,String> generateDartModels(@RequestBody DartModelRequest request) {
        Map<String,String> result = new LinkedHashMap<>();

        for (var schema : request.schemas()) {
            String code = buildDartModel(schema);
            result.put(schema.name() + ".dart", code);
        }

        return result;
    }

    private String buildDartModel(DataSchema schema) {
        StringBuilder sb = new StringBuilder();
        sb.append("// ─────────────────────────────────────────────────────\n");
        sb.append("// GENERATED by Appzillon-New IDE\n");
        sb.append("// Schema: ").append(schema.name()).append("\n");
        sb.append("// ─────────────────────────────────────────────────────\n\n");
        sb.append("class ").append(schema.name()).append(" {\n");

        // Fields
        for (var field : schema.fields()) {
            String dartType = toDartType(field.type(), field.itemType(), field.required());
            sb.append("  final ").append(dartType).append(" ").append(field.name()).append(";\n");
        }
        sb.append("\n");

        // Constructor
        sb.append("  const ").append(schema.name()).append("({\n");
        for (var field : schema.fields()) {
            boolean req = Boolean.TRUE.equals(field.required());
            sb.append("    ").append(req ? "required " : "").append("this.").append(field.name()).append(",\n");
        }
        sb.append("  });\n\n");

        // fromJson
        sb.append("  factory ").append(schema.name()).append(".fromJson(Map<String, dynamic> json) {\n");
        sb.append("    return ").append(schema.name()).append("(\n");
        for (var field : schema.fields()) {
            String accessor = buildJsonAccessor(field, "json");
            sb.append("      ").append(field.name()).append(": ").append(accessor).append(",\n");
        }
        sb.append("    );\n  }\n\n");

        // toJson
        sb.append("  Map<String, dynamic> toJson() => {\n");
        for (var field : schema.fields()) {
            String serializer = buildJsonSerializer(field);
            sb.append("    '").append(field.name()).append("': ").append(serializer).append(",\n");
        }
        sb.append("  };\n\n");

        // copyWith
        sb.append("  ").append(schema.name()).append(" copyWith({\n");
        for (var field : schema.fields()) {
            String dartType = toDartType(field.type(), field.itemType(), false);
            sb.append("    ").append(dartType).append("? ").append(field.name()).append(",\n");
        }
        sb.append("  }) => ").append(schema.name()).append("(\n");
        for (var field : schema.fields()) {
            sb.append("    ").append(field.name()).append(": ").append(field.name()).append(" ?? this.").append(field.name()).append(",\n");
        }
        sb.append("  );\n}\n");

        return sb.toString();
    }

    private String toDartType(String type, String itemType, Boolean required) {
        String nullable = Boolean.TRUE.equals(required) ? "" : "?";
        return switch (type == null ? "dynamic" : type) {
            case "String"   -> "String" + nullable;
            case "int"      -> "int" + nullable;
            case "double"   -> "double" + nullable;
            case "bool"     -> "bool" + nullable;
            case "DateTime" -> "DateTime" + nullable;
            case "List"     -> "List<" + (itemType != null ? itemType : "dynamic") + ">" + nullable;
            case "Object"   -> "Map<String, dynamic>" + nullable;
            default         -> "dynamic";
        };
    }

    private String buildJsonAccessor(FieldDef field, String mapVar) {
        String key = "'" + field.name() + "'";
        boolean req = Boolean.TRUE.equals(field.required());
        return switch (field.type() == null ? "dynamic" : field.type()) {
            case "String"   -> mapVar + "[" + key + "]" + (req ? " as String" : " as String?");
            case "int"      -> mapVar + "[" + key + "]" + (req ? " as int" : " as int?");
            case "double"   -> "((" + mapVar + "[" + key + "] ?? 0) as num).toDouble()";
            case "bool"     -> mapVar + "[" + key + "]" + (req ? " as bool" : " as bool? ?? false");
            case "DateTime" -> "DateTime.tryParse(" + mapVar + "[" + key + "] ?? '')";
            case "List"     -> "(" + mapVar + "[" + key + "] as List?)?.map((e) => e as " + (field.itemType() != null ? field.itemType() : "dynamic") + ").toList() ?? []";
            case "Object"   -> "Map<String, dynamic>.from(" + mapVar + "[" + key + "] as Map? ?? {})";
            default         -> mapVar + "[" + key + "]";
        };
    }

    private String buildJsonSerializer(FieldDef field) {
        return switch (field.type() == null ? "dynamic" : field.type()) {
            case "DateTime" -> field.name() + "?.toIso8601String()";
            case "Object"   -> field.name();
            default         -> field.name();
        };
    }

    // ─────────────────────────────────────────────────────────
    // Records
    // ─────────────────────────────────────────────────────────

    public record TestRequest(
        String method,
        String url,
        List<Map<String,Object>> params,
        String body
    ) {}

    public record DartModelRequest(List<DataSchema> schemas) {}

    public record DataSchema(
        String name,
        String responseType,
        String arrayPath,
        List<FieldDef> fields
    ) {}

    public record FieldDef(
        String name,
        String type,
        String itemType,
        Boolean required,
        String mockValue
    ) {}
}
