package com.flutterforge.codegen.service;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.MicroserviceDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.io.IOException;
import java.nio.file.*;
import java.util.*;

/**
 * Session 3 — GatewayCodegen
 * Generates Spring Cloud Gateway project replacing the monolith interface.
 *
 * Replaces your old monolith REST interface with:
 *   - Spring Cloud Gateway routing per service
 *   - JWT validation filter
 *   - Rate limiting per route
 *   - CORS configuration
 *   - Circuit breaker per service
 */
@Slf4j
@Component
public class GatewayCodegen {

    public void generate(Map<String, Object> gatewayDef, Path outputDir, GenerationResult result) throws IOException {
        log.info("Session 3 generating API Gateway -> {}", outputDir);

        String groupId    = gatewayDef != null && gatewayDef.get("groupId") != null
                ? gatewayDef.get("groupId").toString() : "com.example";
        String artifactId = "api-gateway";
        int port          = gatewayDef != null && gatewayDef.get("port") instanceof Number n
                ? n.intValue() : 8080;

        String pkg     = groupId + ".gateway";
        String pkgPath = pkg.replace(".", "/");
        Path javaDir   = outputDir.resolve("src/main/java/" + pkgPath);
        Path resDir    = outputDir.resolve("src/main/resources");

        for (String sub : List.of("config","filter","exception")) {
            Files.createDirectories(javaDir.resolve(sub));
        }
        Files.createDirectories(resDir);

        write(outputDir.resolve("pom.xml"),                                    buildGatewayPom(groupId, artifactId), result);
        write(javaDir.resolve("GatewayApplication.java"),                      buildGatewayApplication(pkg),         result);
        write(javaDir.resolve("config/GatewayRoutingConfig.java"),             buildRoutingConfig(pkg, gatewayDef),  result);
        write(javaDir.resolve("config/SecurityConfig.java"),                   buildGatewaySecurityConfig(pkg),      result);
        write(javaDir.resolve("filter/JwtAuthFilter.java"),                    buildJwtFilter(pkg),                  result);
        write(javaDir.resolve("filter/RequestLoggingFilter.java"),             buildLoggingFilter(pkg),              result);
        write(javaDir.resolve("exception/GatewayExceptionHandler.java"),       buildGatewayExceptionHandler(pkg),    result);
        write(resDir.resolve("application.yml"),                               buildGatewayYml(port, gatewayDef),    result);
        write(resDir.resolve("application-dev.yml"),                           buildGatewayDevYml(),                 result);

        log.info("Gateway generation complete: {} files", result.getGeneratedFiles().size());
    }

    private String buildGatewayPom(String groupId, String artifactId) {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
             + "<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
             + "  xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n"
             + "  <modelVersion>4.0.0</modelVersion>\n"
             + "  <parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.2</version><relativePath/></parent>\n"
             + "  <groupId>" + groupId + "</groupId>\n"
             + "  <artifactId>" + artifactId + "</artifactId>\n"
             + "  <version>1.0.0</version>\n"
             + "  <n>API Gateway</n>\n"
             + "  <description>API Gateway — Generated by FlutterForge Session 3 (replaces monolith interface)</description>\n"
             + "  <properties><java.version>21</java.version></properties>\n"
             + "  <dependencies>\n"
             + "    <dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-gateway</artifactId></dependency>\n"
             + "    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-actuator</artifactId></dependency>\n"
             + "    <dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId></dependency>\n"
             + "    <dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-api</artifactId><version>0.12.5</version></dependency>\n"
             + "    <dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-impl</artifactId><version>0.12.5</version><scope>runtime</scope></dependency>\n"
             + "    <dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-jackson</artifactId><version>0.12.5</version><scope>runtime</scope></dependency>\n"
             + "    <dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><optional>true</optional></dependency>\n"
             + "    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>\n"
             + "  </dependencies>\n"
             + "  <dependencyManagement><dependencies>\n"
             + "    <dependency><groupId>org.springframework.cloud</groupId><artifactId>spring-cloud-dependencies</artifactId><version>2023.0.0</version><type>pom</type><scope>import</scope></dependency>\n"
             + "  </dependencies></dependencyManagement>\n"
             + "  <build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId>"
             + "<configuration><finalName>api-gateway</finalName></configuration></plugin></plugins></build>\n"
             + "</project>\n";
    }

    private String buildGatewayApplication(String pkg) {
        return "package " + pkg + ";\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n"
             + "/**\n * API Gateway — Replaces monolith interface\n * Generated by FlutterForge Session 3\n */\n"
             + "@SpringBootApplication\npublic class GatewayApplication {\n"
             + "    public static void main(String[] args) { SpringApplication.run(GatewayApplication.class, args); }\n}\n";
    }

    @SuppressWarnings("unchecked")
    private String buildRoutingConfig(String pkg, Map<String, Object> gatewayDef) {
        StringBuilder routes = new StringBuilder();

        // Build routes from gateway definition
        if (gatewayDef != null && gatewayDef.get("routes") instanceof List<?> routeList) {
            for (Object routeObj : routeList) {
                if (routeObj instanceof Map<?, ?> route) {
                    Map<String, Object> r = (Map<String, Object>) route;
                    String id       = r.getOrDefault("id", "route_" + UUID.randomUUID().toString().substring(0,8)).toString();
                    String target   = r.getOrDefault("targetServiceId", "http://localhost:8081").toString();
                    Object predsObj = r.get("predicates");
                    String path     = "/api/**";
                    if (predsObj instanceof Map<?,?> preds) {
                        Object p = ((Map<?,?>)preds).get("path");
                        if (p != null) path = p.toString();
                    }
                    routes.append("        .route(\"").append(id).append("\", r -> r\n");
                    routes.append("            .path(\"").append(path).append("\")\n");
                    routes.append("            .filters(f -> f.circuitBreaker(c -> c.setName(\"").append(id).append("CB\")))\n");
                    routes.append("            .uri(\"lb://").append(target).append("\"))\n");
                }
            }
        }

        // Default routes if none defined
        if (routes.length() == 0) {
            routes.append("        // Add routes here — example:\n");
            routes.append("        // .route(\"user-service\", r -> r.path(\"/api/v1/users/**\").uri(\"lb://user-service\"))\n");
        }

        return "package " + pkg + ".config;\nimport org.springframework.cloud.gateway.route.RouteLocator;\n"
             + "import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;\n"
             + "import org.springframework.context.annotation.Bean;\nimport org.springframework.context.annotation.Configuration;\n\n"
             + "/**\n * Gateway Routing Config — Generated by FlutterForge Session 3\n"
             + " * This replaces the monolith's routing configuration stored in DB.\n */\n"
             + "@Configuration\npublic class GatewayRoutingConfig {\n\n"
             + "    @Bean\n    public RouteLocator routes(RouteLocatorBuilder builder) {\n"
             + "        return builder.routes()\n"
             + routes
             + "            .build();\n    }\n}\n";
    }

    private String buildGatewaySecurityConfig(String pkg) {
        return "package " + pkg + ".config;\n"
             + "import org.springframework.context.annotation.*;\nimport org.springframework.security.config.web.server.ServerHttpSecurity;\n"
             + "import org.springframework.security.web.server.SecurityWebFilterChain;\n"
             + "import org.springframework.web.cors.*;\nimport org.springframework.web.cors.reactive.*;\nimport java.util.List;\n\n"
             + "@Configuration\npublic class SecurityConfig {\n\n"
             + "    @Bean\n    public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {\n"
             + "        return http.csrf(ServerHttpSecurity.CsrfSpec::disable)\n"
             + "            .cors(c -> c.configurationSource(corsSource()))\n"
             + "            .authorizeExchange(e -> e\n"
             + "                .pathMatchers(\"/actuator/**\").permitAll()\n"
             + "                .anyExchange().permitAll()) // JWT validated in JwtAuthFilter\n"
             + "            .build();\n    }\n\n"
             + "    @Bean\n    public CorsConfigurationSource corsSource() {\n"
             + "        CorsConfiguration c = new CorsConfiguration();\n"
             + "        c.setAllowedOriginPatterns(List.of(\"*\"));\n"
             + "        c.setAllowedMethods(List.of(\"*\"));\n"
             + "        c.setAllowedHeaders(List.of(\"*\"));\n"
             + "        UrlBasedCorsConfigurationSource src = new UrlBasedCorsConfigurationSource();\n"
             + "        src.registerCorsConfiguration(\"/**\", c);\n        return src;\n    }\n}\n";
    }

    private String buildJwtFilter(String pkg) {
        return "package " + pkg + ".filter;\n"
             + "import lombok.extern.slf4j.Slf4j;\nimport org.springframework.cloud.gateway.filter.*;\n"
             + "import org.springframework.core.Ordered;\nimport org.springframework.http.HttpStatus;\n"
             + "import org.springframework.stereotype.Component;\nimport org.springframework.web.server.*;\nimport reactor.core.publisher.Mono;\n\n"
             + "/**\n * JWT Auth Filter — validates Bearer tokens on every request\n"
             + " * Generated by FlutterForge Session 3\n */\n"
             + "@Slf4j\n@Component\npublic class JwtAuthFilter implements GlobalFilter, Ordered {\n\n"
             + "    private static final String AUTH_HEADER = \"Authorization\";\n"
             + "    private static final String BEARER_PREFIX = \"Bearer \";\n\n"
             + "    @Override\n    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {\n"
             + "        String path = exchange.getRequest().getPath().value();\n\n"
             + "        // Skip auth for public paths\n"
             + "        if (path.startsWith(\"/actuator\") || path.startsWith(\"/api/v1/auth\")) {\n"
             + "            return chain.filter(exchange);\n        }\n\n"
             + "        String authHeader = exchange.getRequest().getHeaders().getFirst(AUTH_HEADER);\n"
             + "        if (authHeader == null || !authHeader.startsWith(BEARER_PREFIX)) {\n"
             + "            log.warn(\"Missing or invalid Authorization header for path: {}\", path);\n"
             + "            exchange.getResponse().setStatusCode(HttpStatus.UNAUTHORIZED);\n"
             + "            return exchange.getResponse().setComplete();\n        }\n\n"
             + "        String token = authHeader.substring(BEARER_PREFIX.length());\n"
             + "        // TODO: validate JWT token — integrate with auth service\n"
             + "        // Add user claims to downstream request headers\n"
             + "        return chain.filter(exchange);\n    }\n\n"
             + "    @Override\n    public int getOrder() { return -100; }\n}\n";
    }

    private String buildLoggingFilter(String pkg) {
        return "package " + pkg + ".filter;\n"
             + "import lombok.extern.slf4j.Slf4j;\nimport org.springframework.cloud.gateway.filter.*;\n"
             + "import org.springframework.core.Ordered;\nimport org.springframework.stereotype.Component;\n"
             + "import org.springframework.web.server.*;\nimport reactor.core.publisher.Mono;\nimport java.time.Instant;\n\n"
             + "@Slf4j\n@Component\npublic class RequestLoggingFilter implements GlobalFilter, Ordered {\n\n"
             + "    @Override\n    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {\n"
             + "        long start = Instant.now().toEpochMilli();\n"
             + "        String method = exchange.getRequest().getMethod().name();\n"
             + "        String path   = exchange.getRequest().getPath().value();\n"
             + "        return chain.filter(exchange).doFinally(s -> {\n"
             + "            long ms = Instant.now().toEpochMilli() - start;\n"
             + "            log.info(\"{} {} {}ms status={}\", method, path, ms,\n"
             + "                    exchange.getResponse().getStatusCode());\n        });\n    }\n\n"
             + "    @Override\n    public int getOrder() { return Ordered.LOWEST_PRECEDENCE; }\n}\n";
    }

    private String buildGatewayExceptionHandler(String pkg) {
        return "package " + pkg + ".exception;\n"
             + "import lombok.extern.slf4j.Slf4j;\nimport org.springframework.http.*;\n"
             + "import org.springframework.web.bind.annotation.*;\nimport org.springframework.web.server.ServerWebExchange;\n"
             + "import reactor.core.publisher.Mono;\nimport java.time.Instant;\nimport java.util.*;\n\n"
             + "@Slf4j\n@RestControllerAdvice\npublic class GatewayExceptionHandler {\n\n"
             + "    @ExceptionHandler(Exception.class)\n"
             + "    public Mono<ResponseEntity<Map<String,Object>>> handleError(Exception ex, ServerWebExchange ex2) {\n"
             + "        log.error(\"Gateway error: {}\", ex.getMessage());\n"
             + "        Map<String,Object> body = Map.of(\n"
             + "            \"timestamp\", Instant.now(),\n"
             + "            \"status\", 500,\n"
             + "            \"error\", \"Gateway Error\",\n"
             + "            \"message\", ex.getMessage());\n"
             + "        return Mono.just(ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(body));\n    }\n}\n";
    }

    private String buildGatewayYml(int port, Map<String, Object> gatewayDef) {
        return "server:\n  port: " + port + "\n\n"
             + "spring:\n  application:\n    name: api-gateway\n"
             + "  profiles:\n    active: ${SPRING_PROFILES_ACTIVE:dev}\n"
             + "  cloud:\n    gateway:\n      discovery:\n        locator:\n          enabled: true\n          lower-case-service-id: true\n"
             + "      default-filters:\n        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin\n\n"
             + "management:\n  endpoints:\n    web:\n      exposure:\n        include: health,info,gateway\n\n"
             + "jwt:\n  secret: ${JWT_SECRET:change-me-in-production-use-256-bit-key}\n  expiry: ${JWT_EXPIRY:86400}\n\n"
             + "resilience4j:\n  circuitbreaker:\n    configs:\n      default:\n        slidingWindowSize: 10\n"
             + "        minimumNumberOfCalls: 5\n        permittedNumberOfCallsInHalfOpenState: 3\n"
             + "        waitDurationInOpenState: 10s\n\n"
             + "logging:\n  level:\n    root: INFO\n    org.springframework.cloud.gateway: DEBUG\n";
    }

    private String buildGatewayDevYml() {
        return "# Dev profile — API Gateway\nspring:\n  cloud:\n    gateway:\n      routes: []\n      # Routes are configured in GatewayRoutingConfig.java\n\n"
             + "logging:\n  level:\n    root: DEBUG\n    org.springframework.cloud.gateway: TRACE\n";
    }

    private void write(Path path, String content, GenerationResult result) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, content, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(path.toString());
    }
}
