package com.flutterforge.codegen.service;

import com.flutterforge.model.GenerationResult;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;
import java.util.Map;

/**
 * Generates Spring Cloud Gateway configuration.
 * Full implementation in Session 3.
 */
@Slf4j
@Component
public class GatewayCodegen {

    public void generate(Map<String, Object> gatewayDef,
                          Path outputDir,
                          GenerationResult result) throws IOException {
        log.info("Generating API Gateway → {}", outputDir);
        Files.createDirectories(outputDir.resolve("src/main/resources"));

        String placeholder = """
                # API Gateway — generated by FlutterForge
                # Full Spring Cloud Gateway config in Session 3
                server:
                  port: 8080

                spring:
                  application:
                    name: api-gateway
                  cloud:
                    gateway:
                      routes: []
                """;

        Path ymlPath = outputDir.resolve("src/main/resources/application.yml");
        Files.writeString(ymlPath, placeholder,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(ymlPath.toString());
        result.addWarning("GatewayCodegen: full route generation coming in Session 3");
    }
}
