package com.flutterforge.codegen.service;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.MicroserviceDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates a complete Spring Boot 3 microservice project.
 * Full implementation in Session 3.
 */
@Slf4j
@Component
public class SpringBootCodegen {

    public void generateProject(MicroserviceDefinition service,
                                 Path outputDir,
                                 GenerationResult result) throws IOException {
        log.info("Generating Spring Boot project for {} → {}", service.getName(), outputDir);

        // Create basic project structure
        Files.createDirectories(outputDir.resolve("src/main/java/" +
                service.getGroupId().replace(".", "/") + "/" +
                service.getArtifactId().replace("-", "")));
        Files.createDirectories(outputDir.resolve("src/main/resources"));
        Files.createDirectories(outputDir.resolve("src/test/java"));

        // Generate placeholder pom.xml
        String pom = buildPlaceholderPom(service);
        Path pomPath = outputDir.resolve("pom.xml");
        Files.writeString(pomPath, pom,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(pomPath.toString());

        // Generate placeholder application.yml
        String yml = buildPlaceholderYml(service);
        Path ymlPath = outputDir.resolve("src/main/resources/application.yml");
        Files.writeString(ymlPath, yml,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(ymlPath.toString());

        result.addWarning("SpringBootCodegen: full implementation coming in Session 3");
        log.info("Placeholder Spring Boot project created for {}", service.getName());
    }

    private String buildPlaceholderPom(MicroserviceDefinition service) {
        return """
               <?xml version="1.0" encoding="UTF-8"?>
               <project xmlns="http://maven.apache.org/POM/4.0.0"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                        https://maven.apache.org/xsd/maven-4.0.0.xsd">
                 <modelVersion>4.0.0</modelVersion>
                 <parent>
                   <groupId>org.springframework.boot</groupId>
                   <artifactId>spring-boot-starter-parent</artifactId>
                   <version>3.2.2</version>
                 </parent>
                 <groupId>%s</groupId>
                 <artifactId>%s</artifactId>
                 <version>%s</version>
                 <name>%s</name>
                 <description>%s — Generated by FlutterForge</description>
                 <properties>
                   <java.version>21</java.version>
                 </properties>
                 <dependencies>
                   <dependency>
                     <groupId>org.springframework.boot</groupId>
                     <artifactId>spring-boot-starter-web</artifactId>
                   </dependency>
                   <dependency>
                     <groupId>org.springframework.boot</groupId>
                     <artifactId>spring-boot-starter-actuator</artifactId>
                   </dependency>
                   <dependency>
                     <groupId>org.projectlombok</groupId>
                     <artifactId>lombok</artifactId>
                     <optional>true</optional>
                   </dependency>
                   <dependency>
                     <groupId>org.springframework.boot</groupId>
                     <artifactId>spring-boot-starter-test</artifactId>
                     <scope>test</scope>
                   </dependency>
                 </dependencies>
                 <build>
                   <plugins>
                     <plugin>
                       <groupId>org.springframework.boot</groupId>
                       <artifactId>spring-boot-maven-plugin</artifactId>
                     </plugin>
                   </plugins>
                 </build>
               </project>
               """.formatted(
                service.getGroupId(),
                service.getArtifactId(),
                service.getVersion(),
                service.getName(),
                service.getDescription() != null ? service.getDescription() : service.getName()
        );
    }

    private String buildPlaceholderYml(MicroserviceDefinition service) {
        return """
               server:
                 port: %d

               spring:
                 application:
                   name: %s

               management:
                 endpoints:
                   web:
                     exposure:
                       include: health,info
               # Full config generated in Session 3
               """.formatted(
                service.getPort() != null ? service.getPort() : 8080,
                service.getArtifactId()
        );
    }
}
