import { create } from 'zustand'
import { immer } from 'zustand/middleware/immer'
import { subscribeWithSelector } from 'zustand/middleware'
import { v4 as uuidv4 } from 'uuid'
import type {
  FlutterForgeProject,
  ScreenDefinition,
  WidgetNode,
  WidgetType,
} from '../types/widget.schema'

// ─────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────

export interface CanvasSelection {
  widgetIds: string[]
  screenId: string | null
}

export interface HistoryEntry {
  label: string
  screens: Record<string, ScreenDefinition>
}

export interface CanvasState {
  // Project
  project: FlutterForgeProject | null
  projectFilePath: string | null
  isDirty: boolean

  // Active screen
  activeScreenId: string | null

  // Selection
  selection: CanvasSelection

  // Undo/redo
  history: HistoryEntry[]
  historyIndex: number
  canUndo: boolean
  canRedo: boolean

  // UI state
  zoom: number
  gridEnabled: boolean
  snapToGrid: boolean
  gridSize: number
  showProperties: boolean
  showPalette: boolean
  showCopilot: boolean
  isGenerating: boolean
  generationProgress: string

  // Actions — Project
  setProject:         (project: FlutterForgeProject) => void
  newProject:         (name: string, packageName: string) => void
  updateProjectMeta:  (meta: { name?: string; packageName?: string; version?: string; description?: string }) => void
  setFilePath:        (path: string) => void
  markDirty:          () => void
  markClean:          () => void

  // Actions — Screen
  updateTheme:      (patch: Partial<import('../types/widget.schema').AppTheme>) => void
  addScreen:        (name: string, route: string) => string
  deleteScreen:     (screenId: string) => void
  // Asset actions
  addAsset:         (asset: import('../types/widget.schema').AssetDefinition) => void
  removeAsset:      (assetId: string) => void
  updateAsset:      (assetId: string, updates: Partial<import('../types/widget.schema').AssetDefinition>) => void
  setActiveScreen:  (screenId: string) => void
  updateScreen:     (screenId: string, updates: Partial<ScreenDefinition>) => void
  setScreenFromAI:  (screenId: string, screen: ScreenDefinition) => void

  // Actions — Navigation Designer
  setInitialRoute:      (route: string) => void
  setScreenNavPos:      (screenId: string, pos: { x: number; y: number }) => void
  addNavConnection:     (conn: Omit<import('../types/widget.schema').NavConnection, 'id'>) => string
  updateNavConnection:  (connId: string, updates: Partial<import('../types/widget.schema').NavConnection>) => void
  removeNavConnection:  (connId: string) => void

  // Actions — Widget
  addWidget:        (screenId: string, widget: Omit<WidgetNode, 'id'>, parentId?: string) => string
  updateWidget:     (screenId: string, widgetId: string, updates: Partial<WidgetNode>) => void
  deleteWidget:     (screenId: string, widgetId: string) => void
  moveWidget:       (screenId: string, widgetId: string, newParentId: string | null, index: number) => void
  reparentWidget:   (screenId: string, widgetId: string, newParentId: string) => void

  // Actions — Selection
  selectWidget:     (screenId: string, widgetId: string, multi?: boolean) => void
  selectWidgets:    (screenId: string, widgetIds: string[]) => void
  clearSelection:   () => void

  // Actions — History
  pushHistory:      (label: string) => void
  undo:             () => void
  redo:             () => void

  // Actions — Canvas UI
  setZoom:          (zoom: number) => void
  toggleGrid:       () => void
  toggleSnapToGrid: () => void
  togglePalette:    () => void
  toggleProperties: () => void
  toggleCopilot:    () => void
  setGenerating:    (generating: boolean, progress?: string) => void
}

// ─────────────────────────────────────────────────────────
// DEFAULT PROJECT FACTORY
// ─────────────────────────────────────────────────────────

function createDefaultProject(name: string, packageName: string): FlutterForgeProject {
  const welcomeScreenId = 'screen_welcome'
  const scaffoldId      = 'w_scaffold'
  const appBarId        = 'w_appbar'
  const bodyId          = 'w_body'
  const textId          = 'w_text'

  return {
    id:           uuidv4(),
    name,
    packageName,
    version:      '1.0.0',
    description:  'Generated by FlutterForge',
    initialRoute: '/welcome',
    screens: {
      [welcomeScreenId]: {
        id:           welcomeScreenId,
        name:         'WelcomeScreen',
        route:        '/welcome',
        title:        'Welcome',
        rootWidgetId: scaffoldId,
        widgets: {
          [scaffoldId]: {
            id:       scaffoldId,
            type:     'flutter.widgets.Scaffold' as WidgetType,
            props:    {},
            children: [appBarId, bodyId],
          },
          [appBarId]: {
            id:    appBarId,
            type:  'flutter.widgets.AppBar' as WidgetType,
            props: { title: name, centerTitle: true },
          },
          [bodyId]: {
            id:       bodyId,
            type:     'flutter.widgets.Center' as WidgetType,
            props:    {},
            children: [textId],
          },
          [textId]: {
            id:    textId,
            type:  'flutter.widgets.Text' as WidgetType,
            props: {
              data:  'Welcome to ' + name,
              style: { fontSize: 24, fontWeight: 'w500' },
            },
          },
        },
      },
    },
    services:       {},
    stateProviders: {},
    assets:         [],
    dependencies:   {},
    theme: {
      primaryColor:      { hex: '#6200EA' },
      secondaryColor:    { hex: '#03DAC6' },
      tertiaryColor:     { hex: '#EFB8C8' },
      errorColor:        { hex: '#B00020' },
      backgroundColor:   { hex: '#FFFBFE' },
      surfaceColor:      { hex: '#FFFBFE' },
      onPrimaryColor:    { hex: '#FFFFFF' },
      onSecondaryColor:  { hex: '#000000' },
      onBackgroundColor: { hex: '#1C1B1F' },
      onSurfaceColor:    { hex: '#1C1B1F' },
      onErrorColor:      { hex: '#FFFFFF' },
      fontFamily: 'Roboto',
      displayFontSize: 57, headlineFontSize: 32, titleFontSize: 22,
      bodyFontSize: 14, labelFontSize: 12,
      fontWeightBold: 700, fontWeightNormal: 400,
      borderRadiusSmall: 8, borderRadiusMedium: 12,
      borderRadiusLarge: 28, borderRadiusFull: 50,
      appBarElevation: 0, cardElevation: 2, buttonHeight: 48,
      inputBorderStyle: 'outline' as const,
      useMaterial3: true,
      brightness: 'system' as const,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    metadata: {
      targetPlatforms: ['android', 'ios', 'web'],
    },
  }
}

// ─────────────────────────────────────────────────────────
// STORE
// ─────────────────────────────────────────────────────────

export const useCanvasStore = create<CanvasState>()(
  subscribeWithSelector(
    immer((set, get) => ({
      // ── Initial state ────────────────────────────────
      project:            null,
      projectFilePath:    null,
      isDirty:            false,
      activeScreenId:     null,
      selection:          { widgetIds: [], screenId: null },
      history:            [],
      historyIndex:       -1,
      canUndo:            false,
      canRedo:            false,
      zoom:               1.0,
      gridEnabled:        true,
      snapToGrid:         true,
      gridSize:           8,
      showProperties:     true,
      showPalette:        true,
      showCopilot:        false,
      isGenerating:       false,
      generationProgress: '',

      // ── Project actions ──────────────────────────────

      setProject: (project) => set((state) => {
        // Normalise old project data — ensure every screen has widgets: {}
        if (project.screens) {
          for (const sc of Object.values(project.screens)) {
            if (!sc.widgets) (sc as any).widgets = {}
          }
        }
        state.project = project
        state.activeScreenId = Object.keys(project.screens)[0] ?? null
        state.isDirty = false
        state.history = []
        state.historyIndex = -1
        state.canUndo = false
        state.canRedo = false
      }),

      newProject: (name, packageName) => set((state) => {
        const project = createDefaultProject(name, packageName)
        state.project = project
        state.projectFilePath = null
        state.activeScreenId = Object.keys(project.screens)[0] ?? null
        state.isDirty = false
        state.history = []
        state.historyIndex = -1
      }),

      updateProjectMeta: (meta) => set((state) => {
        if (!state.project) return
        if (meta.name        !== undefined) state.project.name        = meta.name
        if (meta.packageName !== undefined) state.project.packageName = meta.packageName
        if (meta.version     !== undefined) state.project.version     = meta.version
        if (meta.description !== undefined) state.project.description = meta.description
        state.isDirty = true
      }),

      setFilePath:  (path) => set((state) => { state.projectFilePath = path.replace(/\\\\/g, '/') }),
      markDirty:    ()     => set((state) => { state.isDirty = true }),
      markClean:    ()     => set((state) => { state.isDirty = false }),

      // ── Screen actions ───────────────────────────────

      updateTheme: (patch) => set((state) => {
        if (state.project) {
          state.project.theme = { ...state.project.theme, ...patch }
          state.isDirty = true
        }
      }),

      addScreen: (name, route) => {
        const id = 'screen_' + uuidv4().substring(0, 8)
        const scaffoldId = 'w_' + uuidv4().substring(0, 8)
        const appBarId   = 'w_' + uuidv4().substring(0, 8)
        const bodyId     = 'w_' + uuidv4().substring(0, 8)

        set((state) => {
          if (!state.project) return
          state.project.screens[id] = {
            id,
            name,
            route,
            title: name.replace('Screen', ''),
            rootWidgetId: scaffoldId,
            widgets: {
              [scaffoldId]: { id: scaffoldId, type: 'flutter.widgets.Scaffold' as WidgetType, props: {}, children: [appBarId, bodyId] },
              [appBarId]:   { id: appBarId,   type: 'flutter.widgets.AppBar' as WidgetType,   props: { title: name.replace('Screen', '') } },
              [bodyId]:     { id: bodyId,     type: 'flutter.widgets.Center' as WidgetType,    props: {} },
            },
          }
          state.activeScreenId = id
          state.isDirty = true
        })
        return id
      },

      deleteScreen: (screenId) => set((state) => {
        if (!state.project) return
        delete state.project.screens[screenId]
        if (state.activeScreenId === screenId) {
          state.activeScreenId = Object.keys(state.project.screens)[0] ?? null
        }
        state.isDirty = true
      }),

      setActiveScreen: (screenId) => set((state) => {
        state.activeScreenId = screenId
        state.selection = { widgetIds: [], screenId }
      }),

      updateScreen: (screenId, updates) => set((state) => {
        if (!state.project?.screens[screenId]) return
        Object.assign(state.project.screens[screenId], updates)
        state.isDirty = true
      }),

      addAsset: (asset) => set((state) => {
        if (!state.project) return
        if (!state.project.assets) state.project.assets = []
        state.project.assets.push(asset)
        state.isDirty = true
      }),

      removeAsset: (assetId) => set((state) => {
        if (!state.project) return
        state.project.assets = (state.project.assets || []).filter(a => a.id !== assetId)
        state.isDirty = true
      }),

      updateAsset: (assetId, updates) => set((state) => {
        if (!state.project) return
        const idx = (state.project.assets || []).findIndex(a => a.id === assetId)
        if (idx !== -1) Object.assign(state.project.assets![idx], updates)
        state.isDirty = true
      }),

      setScreenFromAI: (screenId, screen) => set((state) => {
        if (!state.project) return
        state.project.screens[screenId] = screen
        state.activeScreenId = screenId
        state.isDirty = true
      }),

      // ── Navigation Designer actions ───────────────────

      setInitialRoute: (route) => set((state) => {
        if (!state.project) return
        state.project.initialRoute = route
        state.isDirty = true
      }),

      setScreenNavPos: (screenId, pos) => set((state) => {
        if (!state.project?.screens[screenId]) return
        state.project.screens[screenId].navPos = pos
        state.isDirty = true
      }),

      addNavConnection: (conn) => {
        const id = 'nav_' + Math.random().toString(36).slice(2, 10)
        set((state) => {
          if (!state.project) return
          if (!state.project.navConnections) state.project.navConnections = []
          state.project.navConnections.push({ ...conn, id })
          state.isDirty = true
        })
        return id
      },

      updateNavConnection: (connId, updates) => set((state) => {
        if (!state.project?.navConnections) return
        const idx = state.project.navConnections.findIndex(c => c.id === connId)
        if (idx >= 0) {
          Object.assign(state.project.navConnections[idx], updates)
          state.isDirty = true
        }
      }),

      removeNavConnection: (connId) => set((state) => {
        if (!state.project?.navConnections) return
        state.project.navConnections = state.project.navConnections.filter(c => c.id !== connId)
        state.isDirty = true
      }),

      addWidget: (screenId, widgetDef, parentId) => {
        const id = 'w_' + uuidv4().substring(0, 8)
        set((state) => {
          const screen = state.project?.screens[screenId]
          if (!screen) return
          // Push history before mutation
          state.history = state.history.slice(0, state.historyIndex + 1)
          state.history.push({ label: 'Add ' + (widgetDef.type?.split('.').pop() || 'widget'), screens: JSON.parse(JSON.stringify(state.project!.screens)) })
          if (state.history.length > 50) state.history.shift()
          state.historyIndex = state.history.length - 1
          state.canUndo = true; state.canRedo = false
          // Mutation
          screen.widgets[id] = { ...widgetDef, id } as WidgetNode
          if (parentId && screen.widgets[parentId]) {
            if (!screen.widgets[parentId].children) screen.widgets[parentId].children = []
            screen.widgets[parentId].children!.push(id)
          }
          state.isDirty = true
        })
        return id
      },

      updateWidget: (screenId, widgetId, updates) => set((state) => {
        const widget = state.project?.screens[screenId]?.widgets[widgetId]
        if (!widget) return
        Object.assign(widget, updates)
        if (updates.props) widget.props = { ...widget.props, ...updates.props }
        state.isDirty = true
      }),

      deleteWidget: (screenId, widgetId) => set((state) => {
        const screen = state.project?.screens[screenId]
        if (!screen) return
        state.history = state.history.slice(0, state.historyIndex + 1)
        state.history.push({ label: 'Delete widget', screens: JSON.parse(JSON.stringify(state.project!.screens)) })
        if (state.history.length > 50) state.history.shift()
        state.historyIndex = state.history.length - 1
        state.canUndo = true; state.canRedo = false

        // Remove from parent's children array
        for (const widget of Object.values(screen.widgets)) {
          if (widget.children) {
            widget.children = widget.children.filter(id => id !== widgetId)
          }
        }

        // Recursively delete children
        const deleteRecursive = (id: string) => {
          const w = screen.widgets[id]
          if (!w) return
          w.children?.forEach(deleteRecursive)
          delete screen.widgets[id]
        }
        deleteRecursive(widgetId)

        // Clear selection if deleted widget was selected
        if (state.selection.widgetIds.includes(widgetId)) {
          state.selection.widgetIds = state.selection.widgetIds.filter(id => id !== widgetId)
        }
        state.isDirty = true
      }),

      moveWidget: (screenId, widgetId, newParentId, index) => set((state) => {
        const screen = state.project?.screens[screenId]
        if (!screen) return

        // Remove from current parent
        for (const widget of Object.values(screen.widgets)) {
          if (widget.children) {
            widget.children = widget.children.filter(id => id !== widgetId)
          }
        }

        // Add to new parent
        if (newParentId && screen.widgets[newParentId]) {
          const parent = screen.widgets[newParentId]
          if (!parent.children) parent.children = []
          parent.children.splice(index, 0, widgetId)
        }
        state.isDirty = true
      }),

      reparentWidget: (screenId, widgetId, newParentId) => {
        const index = 0
        get().moveWidget(screenId, widgetId, newParentId, index)
      },

      // ── Selection ────────────────────────────────────

      selectWidget: (screenId, widgetId, multi = false) => set((state) => {
        if (multi) {
          if (state.selection.widgetIds.includes(widgetId)) {
            state.selection.widgetIds = state.selection.widgetIds.filter(id => id !== widgetId)
          } else {
            state.selection.widgetIds.push(widgetId)
          }
        } else {
          state.selection = { widgetIds: [widgetId], screenId }
        }
      }),

      selectWidgets: (screenId, widgetIds) => set((state) => {
        state.selection = { widgetIds, screenId }
      }),

      clearSelection: () => set((state) => {
        state.selection = { widgetIds: [], screenId: state.activeScreenId }
      }),

      // ── History (undo/redo) ──────────────────────────

      pushHistory: (label) => set((state) => {
        if (!state.project) return
        // Truncate future history
        state.history = state.history.slice(0, state.historyIndex + 1)
        state.history.push({
          label,
          screens: JSON.parse(JSON.stringify(state.project.screens)),
        })
        // Keep max 50 history entries
        if (state.history.length > 50) state.history.shift()
        state.historyIndex = state.history.length - 1
        state.canUndo = state.historyIndex > 0
        state.canRedo = false
      }),

      undo: () => set((state) => {
        if (!state.project || state.historyIndex <= 0) return
        state.historyIndex--
        state.project.screens = JSON.parse(JSON.stringify(state.history[state.historyIndex].screens))
        state.canUndo = state.historyIndex > 0
        state.canRedo = true
        state.isDirty = true
      }),

      redo: () => set((state) => {
        if (!state.project || state.historyIndex >= state.history.length - 1) return
        state.historyIndex++
        state.project.screens = JSON.parse(JSON.stringify(state.history[state.historyIndex].screens))
        state.canUndo = true
        state.canRedo = state.historyIndex < state.history.length - 1
        state.isDirty = true
      }),

      // ── Canvas UI ────────────────────────────────────

      setZoom:          (zoom)  => set((s) => { s.zoom = Math.max(0.25, Math.min(3, zoom)) }),
      toggleGrid:       ()      => set((s) => { s.gridEnabled  = !s.gridEnabled }),
      toggleSnapToGrid: ()      => set((s) => { s.snapToGrid   = !s.snapToGrid }),
      togglePalette:    ()      => set((s) => { s.showPalette  = !s.showPalette }),
      toggleProperties: ()      => set((s) => { s.showProperties = !s.showProperties }),
      toggleCopilot:    ()      => set((s) => { s.showCopilot  = !s.showCopilot }),

      setGenerating: (generating, progress = '') => set((s) => {
        s.isGenerating = generating
        s.generationProgress = progress
      }),
    }))
  )
)

// ─────────────────────────────────────────────────────────
// SELECTORS (memoised)
// ─────────────────────────────────────────────────────────

export const selectActiveScreen = (state: CanvasState): ScreenDefinition | null =>
  state.activeScreenId && state.project
    ? state.project.screens[state.activeScreenId] ?? null
    : null

export const selectSelectedWidgets = (state: CanvasState): WidgetNode[] => {
  const screen = selectActiveScreen(state)
  if (!screen) return []
  return state.selection.widgetIds
    .map(id => screen.widgets[id])
    .filter(Boolean)
}

export const selectWidget = (screenId: string, widgetId: string) =>
  (state: CanvasState): WidgetNode | null =>
    state.project?.screens[screenId]?.widgets[widgetId] ?? null
