package com.flutterforge.codegen.infra;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.MicroserviceDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates CI/CD pipeline configs per microservice.
 * Full implementation in Session 6.
 */
@Slf4j
@Component
public class CiCdCodegen {

    public void generate(MicroserviceDefinition service,
                          Path outputDir,
                          GenerationResult result) throws IOException {
        log.info("Generating CI/CD pipeline for {}", service.getName());

        Path githubDir = outputDir.resolve(".github/workflows");
        Files.createDirectories(githubDir);

        String workflow = """
                # Generated by FlutterForge — Full pipeline in Session 6
                name: %s CI
                on:
                  push:
                    branches: [ main, develop ]
                  pull_request:
                    branches: [ main ]
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: actions/checkout@v4
                      - uses: actions/setup-java@v4
                        with:
                          java-version: '21'
                          distribution: 'temurin'
                      - run: mvn clean install
                """.formatted(service.getName());

        Path workflowPath = githubDir.resolve("ci.yml");
        Files.writeString(workflowPath, workflow,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(workflowPath.toString());
        result.addWarning("CiCdCodegen: full pipeline with Docker build/push in Session 6");
    }
}
