package com.flutterforge.codegen.infra;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.MicroserviceDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates Dockerfile per microservice.
 * Full implementation in Session 6.
 */
@Slf4j
@Component
public class DockerCodegen {

    public void generate(MicroserviceDefinition.InfraDefinition.DockerDefinition docker,
                          MicroserviceDefinition service,
                          Path outputDir,
                          GenerationResult result) throws IOException {
        log.info("Generating Dockerfile for {}", service.getName());
        Files.createDirectories(outputDir);

        String dockerfile = """
                # Generated by FlutterForge — Full multi-stage build in Session 6
                FROM eclipse-temurin:21-jre-alpine
                WORKDIR /app
                COPY target/%s.jar app.jar
                EXPOSE %d
                ENTRYPOINT ["java", "-jar", "app.jar"]
                """.formatted(
                service.getArtifactId(),
                docker != null && docker.getExposedPort() != null ? docker.getExposedPort() : 8080
        );

        Path dockerfilePath = outputDir.resolve("Dockerfile");
        Files.writeString(dockerfilePath, dockerfile,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(dockerfilePath.toString());
    }
}
