package com.flutterforge.codegen.infra;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.ServiceGraphDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates docker-compose.yml for local development.
 * Wires all services + Kafka + PostgreSQL + Redis.
 * Full implementation in Session 6.
 */
@Slf4j
@Component
public class DockerComposeCodegen {

    public void generate(ServiceGraphDefinition graph,
                          Path outputDir,
                          GenerationResult result) throws IOException {
        log.info("Generating docker-compose for service graph: {}", graph.getName());
        Files.createDirectories(outputDir);

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by FlutterForge — Full compose in Session 6\n");
        sb.append("version: '3.9'\n\nservices:\n\n");

        sb.append("  # Infrastructure\n");
        sb.append("  postgres:\n");
        sb.append("    image: postgres:16-alpine\n");
        sb.append("    environment:\n");
        sb.append("      POSTGRES_PASSWORD: postgres\n");
        sb.append("    ports:\n      - '5432:5432'\n\n");

        sb.append("  redis:\n");
        sb.append("    image: redis:7-alpine\n");
        sb.append("    ports:\n      - '6379:6379'\n\n");

        sb.append("  kafka:\n");
        sb.append("    image: confluentinc/cp-kafka:7.5.0\n");
        sb.append("    ports:\n      - '9092:9092'\n\n");

        if (graph.getServices() != null) {
            sb.append("  # Microservices — full config in Session 6\n");
            graph.getServices().forEach((id, svc) -> {
                sb.append("  ").append(svc.getArtifactId()).append(":\n");
                sb.append("    image: ").append(svc.getArtifactId()).append(":latest\n");
                sb.append("    ports:\n      - '")
                  .append(svc.getPort()).append(":").append(svc.getPort()).append("'\n\n");
            });
        }

        Path composePath = outputDir.resolve("docker-compose.yml");
        Files.writeString(composePath, sb.toString(),
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(composePath.toString());
    }
}
