package com.flutterforge.codegen.infra;

import com.flutterforge.model.GenerationResult;
import com.flutterforge.model.MicroserviceDefinition;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates Helm charts per microservice.
 * Full implementation in Session 6.
 */
@Slf4j
@Component
public class HelmCodegen {

    public void generate(MicroserviceDefinition service,
                          Path outputDir,
                          GenerationResult result) throws IOException {
        log.info("Generating Helm chart for {}", service.getName());

        Path helmDir = outputDir.resolve("helm/" + service.getArtifactId());
        Files.createDirectories(helmDir.resolve("templates"));

        String chartYaml = """
                apiVersion: v2
                name: %s
                description: Generated by FlutterForge
                version: %s
                # Full Helm chart templates in Session 6
                """.formatted(service.getArtifactId(), service.getVersion());

        Path chartPath = helmDir.resolve("Chart.yaml");
        Files.writeString(chartPath, chartYaml,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        result.getGeneratedFiles().add(chartPath.toString());
        result.addWarning("HelmCodegen: full chart templates coming in Session 6");
    }
}
