import type { InterfaceDefinition, DataFile, SchemaField } from '../types/api-integration.types'
import type { ScreenDefinition, WidgetNode } from '../types/widget.schema'

// ─────────────────────────────────────────────────────────────────────────────
// ENTRY POINT
// Generate all code for a screen's API bindings
// Returns: Map of filename → dart code string
// ─────────────────────────────────────────────────────────────────────────────

export function generateApiCode(
  screen: ScreenDefinition,
  interfaces: InterfaceDefinition[],
  dataFiles: DataFile[],
): Map<string, string> {
  const output = new Map<string, string>()

  // Collect all interfaces used by bindings on this screen
  const usedIfcIds = new Set<string>()
  collectBindings(Object.values(screen.widgets || {})).forEach(b => {
    if (b.interfaceId) usedIfcIds.add(b.interfaceId)
  })
  if (usedIfcIds.size === 0) return output

  const usedInterfaces = interfaces.filter(i => usedIfcIds.has(i.id))

  for (const ifc of usedInterfaces) {
    const df = dataFiles.find(d => d.id === ifc.responseSchemaId)
    if (!df) continue

    // 1. Dart model file
    const modelCode = generateDartModel(df)
    const modelFile = toSnakeCase(df.name) + '.dart'
    output.set('lib/models/' + modelFile, modelCode)

    // 2. Riverpod provider + controller with hooks
    const providerCode = generateProvider(ifc, df)
    const providerFile = toSnakeCase(ifc.name) + '_provider.dart'
    output.set('lib/providers/' + providerFile, providerCode)
  }

  // 3. Screen widget code with bindings wired
  const screenCode = generateScreenWidget(screen, usedInterfaces, dataFiles)
  const screenFile = toSnakeCase(screen.name) + '_bindings.dart'
  output.set('lib/screens/' + screenFile, screenCode)

  return output
}

// ─────────────────────────────────────────────────────────────────────────────
// DART MODEL GENERATOR
// ─────────────────────────────────────────────────────────────────────────────

export function generateDartModel(df: DataFile): string {
  const lines: string[] = [
    '// ─────────────────────────────────────────────────────',
    `// ${df.name} — GENERATED by Appzillon-New IDE`,
    `// Response type: ${df.responseType}`,
    '// DO NOT EDIT — regenerated on every build',
    '// ─────────────────────────────────────────────────────',
    '',
  ]

  // Generate main model class
  lines.push(...buildModelClass(df.name, df.fields, df))

  // Generate nested classes for Object/List<Object> fields
  const nested = collectNestedModels(df.fields, df.name)
  for (const [className, fields] of nested) {
    lines.push('', ...buildModelClass(className, fields))
  }

  return lines.join('\n')
}

function buildModelClass(className: string, fields: SchemaField[], df?: DataFile): string[] {
  const lines: string[] = [`class ${className} {`]

  // Final fields
  for (const f of fields) {
    const dt = dartType(f)
    lines.push(`  final ${dt} ${f.name};`)
  }
  lines.push('')

  // Constructor
  lines.push(`  const ${className}({`)
  for (const f of fields) {
    lines.push(`    ${f.required ? 'required ' : ''}this.${f.name},`)
  }
  lines.push('  });')
  lines.push('')

  // factory fromJson — handle different response types
  if (df?.responseType === 'BARE_ARRAY' || df?.responseType === 'WRAPPED_ARRAY') {
    // Static list parser
    const arrayPath = df.arrayPath || 'data'
    const unwrap = df.responseType === 'WRAPPED_ARRAY'
      ? `final list = (json['${arrayPath}'] as List? ?? []);`
      : `final list = (json is List ? json : json['${arrayPath}'] as List? ?? []);`
    lines.push(`  static List<${className}> listFromJson(dynamic json) {`)
    lines.push(`    ${unwrap}`)
    lines.push(`    return list.map((e) => ${className}.fromJson(e as Map<String, dynamic>)).toList();`)
    lines.push('  }')
    lines.push('')
  }

  lines.push(`  factory ${className}.fromJson(Map<String, dynamic> json) {`)
  lines.push(`    return ${className}(`)
  for (const f of fields) {
    lines.push(`      ${f.name}: ${jsonAccessor(f)},`)
  }
  lines.push('    );')
  lines.push('  }')
  lines.push('')

  // toJson
  lines.push(`  Map<String, dynamic> toJson() => {`)
  for (const f of fields) {
    lines.push(`    '${f.name}': ${jsonSerializer(f)},`)
  }
  lines.push('  };')
  lines.push('')

  // copyWith
  lines.push(`  ${className} copyWith({`)
  for (const f of fields) {
    lines.push(`    ${dartTypeNullable(f)}? ${f.name},`)
  }
  lines.push('  }) =>')
  lines.push(`    ${className}(`)
  for (const f of fields) {
    lines.push(`      ${f.name}: ${f.name} ?? this.${f.name},`)
  }
  lines.push('    );')
  lines.push('}')

  return lines
}

function collectNestedModels(fields: SchemaField[], parentName: string): Map<string, SchemaField[]> {
  const result = new Map<string, SchemaField[]>()
  for (const f of fields) {
    if (f.type === 'Object' && f.fields && f.fields.length > 0) {
      const name = parentName + capitalize(f.name)
      result.set(name, f.fields)
      const nested = collectNestedModels(f.fields, name)
      nested.forEach((v, k) => result.set(k, v))
    }
    if (f.type === 'List' && f.fields && f.fields.length > 0) {
      const name = capitalize(f.itemType as string || (parentName + capitalize(f.name) + 'Item'))
      result.set(name, f.fields)
    }
  }
  return result
}

// ─────────────────────────────────────────────────────────────────────────────
// PROVIDER GENERATOR
// ─────────────────────────────────────────────────────────────────────────────

export function generateProvider(ifc: InterfaceDefinition, df: DataFile): string {
  const modelName   = df.name
  const ctrlName    = capitalize(ifc.name) + 'Controller'
  const provName    = ifc.name[0].toLowerCase() + ifc.name.slice(1) + 'Provider'
  const isList      = df.responseType === 'BARE_ARRAY' || df.responseType === 'WRAPPED_ARRAY'
  const stateType   = isList ? `List<${modelName}>` : modelName

  const authLine = ifc.authType === 'bearer'
    ? `      headers: {'Authorization': 'Bearer \${await AzSession.instance.getToken()}'},`
    : ifc.authType === 'apiKey'
    ? `      headers: {'${ifc.authHeaderName || 'X-API-Key'}': AzConfig.apiKey},`
    : ''

  const parseResponse = isList
    ? `${modelName}.listFromJson(raw)`
    : `${modelName}.fromJson(raw as Map<String, dynamic>)`

  const hasOnBeforeCall = ifc.hooks.onBeforeCall.trim().replace(/return request;/, '').trim() !== ''
  const hasOnResponse   = ifc.hooks.onResponse.trim().replace(/return raw;/, '').trim() !== ''
  const hasOnError      = ifc.hooks.onError.trim() !== ''

  const onBeforeBody = hasOnBeforeCall ? ifc.hooks.onBeforeCall : '    return request;'
  const onResponseBody = hasOnResponse ? ifc.hooks.onResponse   : '    return raw;'
  const onErrorBody  = hasOnError ? ifc.hooks.onError : `    AzLogger.error('${ifc.name} failed: \$error (\$statusCode)');`

  return `// ─────────────────────────────────────────────────────
// ${ctrlName} — GENERATED by Appzillon-New IDE
// Interface: ${ifc.name}  •  ${ifc.method} ${ifc.urlPath}
// ─────────────────────────────────────────────────────

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../appzillon/appzillon.dart';
import '../models/${toSnakeCase(modelName)}.dart';

class ${ctrlName} extends StateNotifier<AsyncValue<${stateType}>> {
  ${ctrlName}(this.ref) : super(const AsyncValue.loading())${ifc.triggerType === 'onScreenLoad' ? ' { load(); }' : ';'}
  final Ref ref;

  Future<void> load() async {
    state = const AsyncValue.loading();
    try {
      // ── Build request ─────────────────────────────────
      var request = AzRequest(
        url: AzConfig.baseUrl + '${ifc.urlPath}',
${authLine}      );
      request = onBeforeCall(request);

      // ── Call API ──────────────────────────────────────
      final raw = await AzServer.instance.${ifc.method.toLowerCase()}(
        request.url,
        headers: request.headers,
      );

      // ── Transform & parse ─────────────────────────────
      final transformed = onResponse(raw as Map<String, dynamic>);
      state = AsyncValue.data(${parseResponse});

    } catch (e, st) {
      onError(e, (e is AzServerException) ? e.statusCode : 0);
      state = AsyncValue.error(e, st);
    }
  }

  // ── Developer hooks — fill in or leave empty ──────────

  /// Called before the HTTP request is sent.
  /// Add custom headers, inject params, attach signatures here.
  AzRequest onBeforeCall(AzRequest request) {
${onBeforeBody}
  }

  /// Called after a successful response, before widgets receive data.
  /// Filter, sort, enrich, or calculate derived fields here.
  Map<String, dynamic> onResponse(Map<String, dynamic> raw) {
${onResponseBody}
  }

  /// Called on any API error.
  /// Redirect on 401, show dialogs for business errors, etc.
  void onError(dynamic error, int statusCode) {
${onErrorBody}
  }
}

final ${provName} = StateNotifierProvider.autoDispose<${ctrlName}, AsyncValue<${stateType}>>(
  (ref) => ${ctrlName}(ref),
);
`
}

// ─────────────────────────────────────────────────────────────────────────────
// SCREEN BINDINGS GENERATOR
// ─────────────────────────────────────────────────────────────────────────────

function generateScreenWidget(
  screen: ScreenDefinition,
  usedInterfaces: InterfaceDefinition[],
  dataFiles: DataFile[],
): string {
  const screenClass = screen.name + 'View'
  const providerImports = usedInterfaces.map(ifc =>
    `import '../providers/${toSnakeCase(ifc.name)}_provider.dart';`
  ).join('\n')

  const modelImports = usedInterfaces.map(ifc => {
    const df = dataFiles.find(d => d.id === ifc.responseSchemaId)
    return df ? `import '../models/${toSnakeCase(df.name)}.dart';` : ''
  }).filter(Boolean).join('\n')

  // Collect all bindings from all widgets
  const widgets = Object.values(screen.widgets || {})
  const bindings = collectBindings(widgets)

  // Group by interface
  const byIfc = new Map<string, typeof bindings>()
  for (const b of bindings) {
    if (!byIfc.has(b.interfaceId)) byIfc.set(b.interfaceId, [])
    byIfc.get(b.interfaceId)!.push(b)
  }

  // Build watch statements
  const watchLines = usedInterfaces.map(ifc => {
    const provName = ifc.name[0].toLowerCase() + ifc.name.slice(1) + 'Provider'
    return `    final ${ifc.name}Async = ref.watch(${provName});`
  }).join('\n')

  // Build bound widget method for each interface
  const bindingMethods = usedInterfaces.map(ifc => {
    const df = dataFiles.find(d => d.id === ifc.responseSchemaId)
    if (!df) return ''
    const isList = df.responseType === 'BARE_ARRAY' || df.responseType === 'WRAPPED_ARRAY'
    const modelName = df.name
    const paramType = isList ? `List<${modelName}>` : modelName

    return `
  Widget _build${capitalize(ifc.name)}(${paramType} data) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Auto-generated bindings from canvas
${generateBoundWidgets(byIfc.get(ifc.id) || [], ifc, df)}
      ],
    );
  }`
  }).join('\n')

  return `// ─────────────────────────────────────────────────────
// ${screenClass} — GENERATED by Appzillon-New IDE
// Screen: ${screen.name}
// ─────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../appzillon/appzillon.dart';
${providerImports}
${modelImports}

class ${screenClass} extends ConsumerWidget {
  const ${screenClass}({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
${watchLines}

    return Scaffold(
      body: SafeArea(
        child: ${usedInterfaces.length === 1 ? buildAsyncWidget(usedInterfaces[0]) : buildMultiAsyncWidget(usedInterfaces)},
      ),
    );
  }
${bindingMethods}
}
`
}

function buildAsyncWidget(ifc: InterfaceDefinition): string {
  return `${ifc.name}Async.when(
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (e, _) => Center(child: Text('Error: \$e')),
          data: (data) => _build${capitalize(ifc.name)}(data),
        )`
}

function buildMultiAsyncWidget(ifcs: InterfaceDefinition[]): string {
  return `Column(children: [
${ifcs.map(ifc => `          ${ifc.name}Async.when(
            loading: () => const SizedBox.shrink(),
            error: (e, _) => const SizedBox.shrink(),
            data: (data) => _build${capitalize(ifc.name)}(data),
          ),`).join('\n')}
        ])`
}

function generateBoundWidgets(
  bindings: ReturnType<typeof collectBindings>,
  ifc: InterfaceDefinition,
  df: DataFile,
): string {
  if (bindings.length === 0) return '        // No bindings defined'
  const isList = df.responseType === 'BARE_ARRAY' || df.responseType === 'WRAPPED_ARRAY'

  return bindings.map(b => {
    const accessor = buildAccessor(b.fieldPath, isList ? 'item' : 'data', df)
    const formatted = buildFormatCall(accessor, b.format, b.formatArg)
    const visibility = b.visibilityExpr ? `if (${b.visibilityExpr.replace(/(\w+)/g, `data.$1`)}) ` : ''

    if (b.isListBinding && isList) {
      return `        ${visibility}ListView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          itemCount: data.length,
          itemBuilder: (context, index) {
            final item = data[index];
            return Text(item.toString()); // TODO: customise item template
          },
        ),`
    }

    return `        // Widget: ${b.widgetId}  •  ${b.targetProp} ← ${b.fieldPath}
        ${visibility}Text(${formatted}.toString()),`
  }).join('\n')
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

interface BindingInfo {
  widgetId:      string
  interfaceId:   string
  fieldPath:     string
  targetProp:    string
  format:        string
  formatArg?:    string
  visibilityExpr?: string
  isListBinding?: boolean
}

function collectBindings(widgets: WidgetNode[]): BindingInfo[] {
  const out: BindingInfo[] = []
  for (const w of widgets) {
    if ((w as any).apiBinding?.interfaceId) {
      const b = (w as any).apiBinding
      out.push({ widgetId: w.id, interfaceId: b.interfaceId, fieldPath: b.fieldPath,
        targetProp: b.targetProp, format: b.format, formatArg: b.formatArg,
        visibilityExpr: b.visibilityExpr, isListBinding: b.isListBinding })
    }
  }
  return out
}

function buildAccessor(fieldPath: string, root: string, df: DataFile): string {
  // Converts "groups[].memberCount" → "data.groups.isNotEmpty ? data.groups.first.memberCount : null"
  const parts = fieldPath.split('.')
  let accessor = root
  for (const p of parts) {
    if (p.endsWith('[]')) {
      accessor += '.' + p.slice(0,-2)
    } else {
      accessor += '.' + p
    }
  }
  return accessor
}

function buildFormatCall(accessor: string, format: string, arg?: string): string {
  switch (format) {
    case 'currency':    return `AzUtils.formatCurrency(${accessor})`
    case 'percentage':  return `'\${(${accessor} as num).toStringAsFixed(1)}%'`
    case 'uppercase':   return `${accessor}.toString().toUpperCase()`
    case 'lowercase':   return `${accessor}.toString().toLowerCase()`
    case 'date':        return `AzUtils.formatDate(${accessor})`
    case 'dateTime':    return `AzUtils.formatDateTime(${accessor})`
    case 'truncate':    return `AzUtils.truncate(${accessor}.toString(), ${arg || 20})`
    default:            return `${accessor}`
  }
}

function dartType(f: SchemaField): string {
  const n = f.required ? '' : '?'
  switch (f.type) {
    case 'String':   return `String${n}`
    case 'int':      return `int${n}`
    case 'double':   return `double${n}`
    case 'bool':     return `bool${n}`
    case 'DateTime': return `DateTime${n}`
    case 'List':     return `List<${f.itemType || 'dynamic'}>${n}`
    case 'Object':   return `Map<String, dynamic>${n}`
    default:         return 'dynamic'
  }
}

function dartTypeNullable(f: SchemaField): string {
  return dartType({ ...f, required: false }).replace(/\?$/, '')
}

function jsonAccessor(f: SchemaField): string {
  const k = `'${f.name}'`
  const req = f.required
  switch (f.type) {
    case 'String':   return `json[${k}] as String${req ? '' : '?'}`
    case 'int':      return req ? `(json[${k}] as num).toInt()` : `json[${k}] != null ? (json[${k}] as num).toInt() : null`
    case 'double':   return req ? `(json[${k}] as num).toDouble()` : `json[${k}] != null ? (json[${k}] as num).toDouble() : null`
    case 'bool':     return `json[${k}] as bool${req ? '' : '? ?? false'}`
    case 'DateTime': return `DateTime.tryParse(json[${k}] as String? ?? '')`
    case 'List':     {
      const it = f.itemType || 'dynamic'
      const isPrimitive = ['String','int','double','bool'].includes(it)
      if (isPrimitive) return `(json[${k}] as List?)?.map((e) => e as ${it}).toList() ?? []`
      return `(json[${k}] as List?)?.map((e) => ${it}.fromJson(e as Map<String,dynamic>)).toList() ?? []`
    }
    case 'Object':   return `Map<String,dynamic>.from(json[${k}] as Map? ?? {})`
    default:         return `json[${k}]`
  }
}

function jsonSerializer(f: SchemaField): string {
  if (f.type === 'DateTime') return `${f.name}?.toIso8601String()`
  if (f.type === 'List' && f.itemType && !['String','int','double','bool'].includes(f.itemType))
    return `${f.name}${f.required?'':' ?? []'}.map((e) => e.toJson()).toList()`
  return f.name
}

function toSnakeCase(s: string): string {
  return s.replace(/([A-Z])/g, (_, l, i) => (i > 0 ? '_' : '') + l.toLowerCase())
    .replace(/^_/, '').replace(/__+/g, '_')
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
