package com.flutterforge.codegen.dart;

import com.flutterforge.model.FlutterForgeProject;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import java.util.Map;

/**
 * DartThemeCodegen — generates lib/utils/app_theme.dart
 * from the full AppTheme defined in the IDE Theme Editor.
 *
 * Output: complete Material 3 ThemeData with:
 *   - ColorScheme.fromSeed (primary / secondary / tertiary / error)
 *   - Google Fonts typography (if non-Roboto font selected)
 *   - Full type scale (display / headline / title / body / label)
 *   - Shape system (small / medium / large border radius)
 *   - Component themes: AppBar, Card, Buttons, TextField,
 *     Dialog, BottomSheet, Chip, FAB
 *   - Light + dark theme via single _buildTheme(Brightness)
 *   - ThemeMode helper
 */
@Slf4j
@Component
public class DartThemeCodegen {

    public String generate(FlutterForgeProject.AppTheme theme) {
        log.debug("Generating Material 3 theme");

        String primary    = extractHex(theme, "primaryColor",    "6200EA");
        String secondary  = extractHex(theme, "secondaryColor",  "03DAC6");
        String tertiary   = extractHex(theme, "tertiaryColor",   "EFB8C8");
        String error      = extractHex(theme, "errorColor",      "B00020");
        String onPrimary  = extractHex(theme, "onPrimaryColor",  "FFFFFF");
        String background = extractHex(theme, "backgroundColor", "FFFBFE");
        String surface    = extractHex(theme, "surfaceColor",    "FFFBFE");
        String onSurface  = extractHex(theme, "onSurfaceColor",  "1C1B1F");

        String  fontFamily   = extractStr(theme, "fontFamily",       "Roboto");
        int     displaySz    = extractInt(theme, "displayFontSize",  57);
        int     headlineSz   = extractInt(theme, "headlineFontSize", 32);
        int     titleSz      = extractInt(theme, "titleFontSize",    22);
        int     bodySz       = extractInt(theme, "bodyFontSize",     14);
        int     labelSz      = extractInt(theme, "labelFontSize",    12);
        int     weightBold   = extractInt(theme, "fontWeightBold",   700);
        int     weightNormal = extractInt(theme, "fontWeightNormal", 400);

        int     brSmall      = extractInt(theme, "borderRadiusSmall",   8);
        int     brMedium     = extractInt(theme, "borderRadiusMedium", 12);
        int     brLarge      = extractInt(theme, "borderRadiusLarge",  28);

        int     appBarElev   = extractInt(theme, "appBarElevation",  0);
        int     cardElev     = extractInt(theme, "cardElevation",    2);
        int     btnHeight    = extractInt(theme, "buttonHeight",     48);
        String  inputStyle   = extractStr(theme, "inputBorderStyle", "outline");
        boolean m3           = theme == null || theme.isUseMaterial3();
        String  brightnessStr= theme != null && theme.getBrightness() != null
                                 ? theme.getBrightness() : "system";

        boolean useGoogleFonts = !"Roboto".equals(fontFamily);
        String  fontPkg        = fontFamily.replace(" ", "").toLowerCase();

        StringBuilder sb = new StringBuilder();

        // Imports
        sb.append("import 'package:flutter/material.dart';\n");
        if (useGoogleFonts) sb.append("import 'package:google_fonts/google_fonts.dart';\n");
        sb.append("\n");
        sb.append("// ─────────────────────────────────────────────────────────\n");
        sb.append("// app_theme.dart — AUTO-GENERATED by Appzillon-New IDE\n");
        sb.append("// DO NOT EDIT — regenerated from Theme Editor on every save\n");
        sb.append("// ─────────────────────────────────────────────────────────\n\n");

        sb.append("abstract class AppTheme {\n");
        sb.append("  AppTheme._();\n\n");

        // Seed colors
        sb.append("  // ── Seed colors ──────────────────────────────────────────\n");
        sb.append("  static const Color primary    = Color(0xFF").append(primary).append(");\n");
        sb.append("  static const Color secondary  = Color(0xFF").append(secondary).append(");\n");
        sb.append("  static const Color tertiary   = Color(0xFF").append(tertiary).append(");\n");
        sb.append("  static const Color error      = Color(0xFF").append(error).append(");\n");
        sb.append("  static const Color background = Color(0xFF").append(background).append(");\n");
        sb.append("  static const Color surface    = Color(0xFF").append(surface).append(");\n");
        sb.append("  static const Color onPrimary  = Color(0xFF").append(onPrimary).append(");\n");
        sb.append("  static const Color onSurface  = Color(0xFF").append(onSurface).append(");\n\n");

        // Shape scale
        sb.append("  // ── Shape scale ──────────────────────────────────────────\n");
        sb.append("  static const double radiusSmall  = ").append(brSmall).append(";\n");
        sb.append("  static const double radiusMedium = ").append(brMedium).append(";\n");
        sb.append("  static const double radiusLarge  = ").append(brLarge).append(";\n\n");

        // Google Fonts helper
        if (useGoogleFonts) {
            sb.append("  // ── Typography (Google Fonts: ").append(fontFamily).append(") ─────────────────\n");
            sb.append("  static TextTheme get _textTheme =>\n");
            sb.append("    GoogleFonts.").append(fontPkg).append("TextTheme();\n\n");
        }

        // Public API
        sb.append("  static ThemeData get lightTheme => _build(Brightness.light);\n");
        sb.append("  static ThemeData get darkTheme  => _build(Brightness.dark);\n\n");

        String themeMode = switch (brightnessStr) {
            case "light" -> "ThemeMode.light";
            case "dark"  -> "ThemeMode.dark";
            default      -> "ThemeMode.system";
        };
        sb.append("  static ThemeMode get themeMode  => ").append(themeMode).append(";\n\n");

        // _build
        sb.append("  static ThemeData _build(Brightness brightness) {\n");
        sb.append("    final scheme = ColorScheme.fromSeed(\n");
        sb.append("      seedColor:  primary,\n");
        sb.append("      secondary:  secondary,\n");
        sb.append("      tertiary:   tertiary,\n");
        sb.append("      error:      error,\n");
        sb.append("      brightness: brightness,\n");
        sb.append("    );\n\n");
        sb.append("    return ThemeData(\n");
        sb.append("      useMaterial3: ").append(m3).append(",\n");
        sb.append("      colorScheme:  scheme,\n");
        sb.append("      brightness:   brightness,\n\n");

        // TextTheme
        sb.append("      textTheme: ");
        if (useGoogleFonts) sb.append("_textTheme.copyWith(\n");
        else sb.append("const TextTheme().copyWith(\n");
        sb.append("        displayLarge:  TextStyle(fontSize: ").append(displaySz)
          .append(", fontWeight: FontWeight.w").append(weightBold).append("),\n");
        sb.append("        headlineLarge: TextStyle(fontSize: ").append(headlineSz)
          .append(", fontWeight: FontWeight.w").append(weightBold).append("),\n");
        sb.append("        titleLarge:    TextStyle(fontSize: ").append(titleSz)
          .append(", fontWeight: FontWeight.w").append(weightBold).append("),\n");
        sb.append("        bodyLarge:     TextStyle(fontSize: ").append(bodySz)
          .append(", fontWeight: FontWeight.w").append(weightNormal).append("),\n");
        sb.append("        bodyMedium:    TextStyle(fontSize: ").append(Math.max(bodySz - 1, 12))
          .append(", fontWeight: FontWeight.w").append(weightNormal).append("),\n");
        sb.append("        labelLarge:    TextStyle(fontSize: ").append(labelSz)
          .append(", fontWeight: FontWeight.w").append(weightBold).append("),\n");
        sb.append("        labelSmall:    TextStyle(fontSize: ").append(Math.max(labelSz - 2, 10))
          .append(", fontWeight: FontWeight.w").append(weightNormal).append("),\n");
        sb.append("      ),\n\n");

        // AppBar
        sb.append("      appBarTheme: const AppBarTheme(\n");
        sb.append("        centerTitle: true,\n");
        sb.append("        elevation:   ").append(appBarElev).append(",\n");
        sb.append("        scrolledUnderElevation: 1,\n");
        sb.append("      ),\n\n");

        // Card
        sb.append("      cardTheme: const CardTheme(\n");
        sb.append("        elevation: ").append(cardElev).append(",\n");
        sb.append("        clipBehavior: Clip.antiAlias,\n");
        sb.append("        shape: RoundedRectangleBorder(\n");
        sb.append("          borderRadius: BorderRadius.all(Radius.circular(radiusMedium))),\n");
        sb.append("      ),\n\n");

        // Buttons
        sb.append("      elevatedButtonTheme: ElevatedButtonThemeData(\n");
        sb.append("        style: ElevatedButton.styleFrom(\n");
        sb.append("          minimumSize: const Size(double.infinity, ").append(btnHeight).append("),\n");
        sb.append("          shape: const StadiumBorder(),\n");
        sb.append("        ),\n");
        sb.append("      ),\n");
        sb.append("      outlinedButtonTheme: OutlinedButtonThemeData(\n");
        sb.append("        style: OutlinedButton.styleFrom(\n");
        sb.append("          minimumSize: const Size(double.infinity, ").append(btnHeight).append("),\n");
        sb.append("          shape: const StadiumBorder(),\n");
        sb.append("        ),\n");
        sb.append("      ),\n");
        sb.append("      textButtonTheme: TextButtonThemeData(\n");
        sb.append("        style: TextButton.styleFrom(\n");
        sb.append("          shape: const StadiumBorder(),\n");
        sb.append("        ),\n");
        sb.append("      ),\n");
        sb.append("      floatingActionButtonTheme: const FloatingActionButtonThemeData(\n");
        sb.append("        shape: CircleBorder(),\n");
        sb.append("      ),\n\n");

        // Input
        sb.append("      inputDecorationTheme: InputDecorationTheme(\n");
        sb.append("        filled: ").append(inputStyle.equals("filled")).append(",\n");
        if (inputStyle.equals("underline")) {
            sb.append("        border: const UnderlineInputBorder(),\n");
        } else {
            sb.append("        border: OutlineInputBorder(\n");
            sb.append("          borderRadius: BorderRadius.circular(radiusMedium / 2)),\n");
        }
        sb.append("        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),\n");
        sb.append("      ),\n\n");

        // Dialog + BottomSheet
        sb.append("      dialogTheme: const DialogTheme(\n");
        sb.append("        shape: RoundedRectangleBorder(\n");
        sb.append("          borderRadius: BorderRadius.all(Radius.circular(radiusLarge))),\n");
        sb.append("      ),\n");
        sb.append("      bottomSheetTheme: const BottomSheetThemeData(\n");
        sb.append("        showDragHandle: true,\n");
        sb.append("        shape: RoundedRectangleBorder(\n");
        sb.append("          borderRadius: BorderRadius.vertical(\n");
        sb.append("            top: Radius.circular(radiusLarge))),\n");
        sb.append("      ),\n\n");

        // Chip
        sb.append("      chipTheme: const ChipThemeData(\n");
        sb.append("        shape: RoundedRectangleBorder(\n");
        sb.append("          borderRadius: BorderRadius.all(Radius.circular(radiusSmall))),\n");
        sb.append("      ),\n");

        sb.append("    );\n");
        sb.append("  }\n");
        sb.append("}\n");

        return sb.toString();
    }

    // ── Extraction helpers ────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private String extractHex(FlutterForgeProject.AppTheme theme, String field, String fallback) {
        if (theme == null) return fallback;
        try {
            String getter = "get" + Character.toUpperCase(field.charAt(0)) + field.substring(1);
            Object colorObj = theme.getClass().getMethod(getter).invoke(theme);
            if (colorObj instanceof Map<?,?> map) {
                Object hex = ((Map<String,Object>) map).get("hex");
                if (hex != null) {
                    String clean = hex.toString().replace("#", "").toUpperCase();
                    return clean.length() == 6 ? clean : fallback;
                }
            }
        } catch (Exception ignored) {}
        return fallback;
    }

    private String extractStr(FlutterForgeProject.AppTheme theme, String field, String fallback) {
        if (theme == null) return fallback;
        try {
            String getter = "get" + Character.toUpperCase(field.charAt(0)) + field.substring(1);
            Object val = theme.getClass().getMethod(getter).invoke(theme);
            return val != null ? val.toString() : fallback;
        } catch (Exception ignored) {}
        return fallback;
    }

    private int extractInt(FlutterForgeProject.AppTheme theme, String field, int fallback) {
        if (theme == null) return fallback;
        try {
            String getter = "get" + Character.toUpperCase(field.charAt(0)) + field.substring(1);
            Object val = theme.getClass().getMethod(getter).invoke(theme);
            if (val instanceof Number n) return n.intValue();
        } catch (Exception ignored) {}
        return fallback;
    }
}
