package com.flutterforge.codegen.dart;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * S7 — GoRouter Codegen
 *
 * Generates router.dart from navConnections[] in app.json.
 * Called by BuildController after all screen dart files are written.
 *
 * Generated file layout:
 *   imports → RouteNames constants → NavigationHelper → GoRouter appRouter
 *
 * Transition mapping:
 *   "push"            → context.push(route)
 *   "pushReplacement" → context.pushReplacement(route)
 *   "go"              → context.go(route)
 */
@Slf4j
@Component
public class DartRouterCodegen {

    /**
     * Generates router.dart source.
     *
     * @param packageName    dart package name, e.g. "fin_edge_bank"
     * @param initialRoute   e.g. "/splash"
     * @param screenEntries  ordered list — each map has keys "name", "route"
     * @param navConnections list of connections — each map has keys:
     *                       "fromName", "toName", "toRoute", "label", "transition"
     * @return complete router.dart source string
     */
    public String generate(
            String packageName,
            String initialRoute,
            List<Map<String, String>> screenEntries,
            List<Map<String, String>> navConnections) {

        if (screenEntries == null || screenEntries.isEmpty()) {
            log.warn("DartRouterCodegen.generate: no screens provided");
            return buildFallbackRouter(initialRoute);
        }

        String initLoc = (initialRoute != null && !initialRoute.isBlank()) ? initialRoute : "/";
        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("// router.dart — AUTO-GENERATED by Appzillon-New IDE (S7 GoRouter Codegen)\n");
        sb.append("// DO NOT EDIT MANUALLY — regenerated on every build from app.json navConnections.\n");
        sb.append("// To modify navigation: use the Navigation Designer in the IDE canvas.\n\n");

        // Imports
        sb.append("import 'package:flutter/material.dart';\n");
        sb.append("import 'package:go_router/go_router.dart';\n\n");
        for (Map<String, String> se : screenEntries) {
            String name = se.get("name");
            if (name == null || name.isBlank()) continue;
            sb.append("import 'package:").append(packageName)
                    .append("/screens/").append(toSnakeCase(name)).append(".dart';\n");
        }
        sb.append("\n");

        // RouteNames constants
        sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
        sb.append("// Route constants — use instead of hard-coded strings\n");
        sb.append("// Usage: context.push(RouteNames.dashboard)\n");
        sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
        sb.append("abstract class RouteNames {\n");
        for (Map<String, String> se : screenEntries) {
            String name  = se.get("name");
            String route = se.get("route");
            if (name == null || route == null) continue;
            sb.append("  static const String ").append(screenToConstName(route))
                    .append(" = '").append(route).append("';\n");
        }
        sb.append("}\n\n");

        // NavigationHelper
        if (navConnections != null && !navConnections.isEmpty()) {
            sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
            sb.append("// NavigationHelper — named static methods for each nav connection\n");
            sb.append("// Usage: NavigationHelper.pushToDashboard(context)\n");
            sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
            sb.append("class NavigationHelper {\n");
            sb.append("  NavigationHelper._();\n\n");

            Set<String> seen = new LinkedHashSet<>();
            for (Map<String, String> nc : navConnections) {
                String toName     = nc.get("toName");
                String toRoute    = nc.get("toRoute");
                String fromName   = nc.get("fromName");
                String label      = nc.get("label");
                String transition = nc.getOrDefault("transition", "push");
                if (toName == null || toRoute == null) continue;

                String methodName = buildMethodName(toName, transition);
                if (!seen.add(methodName)) continue; // deduplicate

                sb.append("  /// ").append(label != null ? label : "Navigate")
                        .append("  (").append(fromName != null ? fromName : "").append(" → ").append(toName).append(")\n");
                sb.append("  static void ").append(methodName)
                        .append("(BuildContext context) => ")
                        .append(buildGoRouterCall(toRoute, transition)).append(";\n\n");
            }
            sb.append("}\n\n");
        }

        // GoRouter
        sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
        sb.append("// appRouter — use as routerConfig: appRouter in MaterialApp.router()\n");
        sb.append("// ─────────────────────────────────────────────────────────────────────────\n");
        sb.append("final GoRouter appRouter = GoRouter(\n");
        sb.append("  initialLocation: '").append(initLoc).append("',\n");
        sb.append("  debugLogDiagnostics: false,\n");
        sb.append("  routes: [\n");
        for (Map<String, String> se : screenEntries) {
            String name  = se.get("name");
            String route = se.get("route");
            if (name == null || route == null) continue;
            sb.append("    GoRoute(\n");
            sb.append("      path: '").append(route).append("',\n");
            sb.append("      builder: (context, state) => const ").append(name).append("(),\n");
            sb.append("    ),\n");
        }
        sb.append("  ],\n");
        sb.append(");\n");

        log.info("DartRouterCodegen: generated router.dart — {} routes, {} nav methods",
                screenEntries.size(), navConnections != null ? navConnections.size() : 0);
        return sb.toString();
    }

    private String buildMethodName(String toName, String transition) {
        String prefix = switch (transition) {
            case "go"              -> "goTo";
            case "pushReplacement" -> "replaceTo";
            default                -> "pushTo";
        };
        return prefix + toName.replace("Screen", "");
    }

    private String buildGoRouterCall(String route, String transition) {
        return switch (transition) {
            case "pushReplacement" -> "context.pushReplacement('" + route + "')";
            case "go"              -> "context.go('" + route + "')";
            default                -> "context.push('" + route + "')";
        };
    }

    /**
     * Derives the RouteNames constant from the ROUTE STRING — not the screen name.
     * Must stay in sync with routeToConstExpr() in DartWidgetCodegen.
     *
     * "/transactions"   → "transactions"
     * "/account-detail" → "accountDetail"
     * "/fixed-deposits" → "fixedDeposits"
     * "/cards"          → "cards"
     */
    private String screenToConstName(String route) {
        String path = (route != null && !route.isBlank()) ? route.replaceFirst("^/", "") : "";
        if (path.isEmpty()) return "splash";
        String[] parts = path.split("-");
        StringBuilder sb = new StringBuilder(parts[0].toLowerCase());
        for (int i = 1; i < parts.length; i++) {
            String p = parts[i];
            if (!p.isEmpty()) {
                sb.append(Character.toUpperCase(p.charAt(0)));
                sb.append(p.substring(1).toLowerCase());
            }
        }
        return sb.toString();
    }

    private String toSnakeCase(String name) {
        if (name == null || name.isBlank()) return "";
        return name.replaceAll("([A-Z]+)([A-Z][a-z])", "$1_$2")
                .replaceAll("([a-z0-9])([A-Z])", "$1_$2")
                .toLowerCase()
                .replaceAll("[^a-z0-9_]", "_")
                .replaceAll("_+", "_")
                .replaceAll("^_|_$", "");
    }

    private String buildFallbackRouter(String initialRoute) {
        String loc = (initialRoute != null && !initialRoute.isBlank()) ? initialRoute : "/";
        return "// router.dart — fallback (no screens found)\n"
                + "import 'package:flutter/material.dart';\n"
                + "import 'package:go_router/go_router.dart';\n\n"
                + "final GoRouter appRouter = GoRouter(\n"
                + "  initialLocation: '" + loc + "',\n"
                + "  routes: [\n"
                + "    GoRoute(\n"
                + "      path: '" + loc + "',\n"
                + "      builder: (c, s) => const Scaffold(\n"
                + "          body: Center(child: Text('No screens configured'))),\n"
                + "    ),\n"
                + "  ],\n"
                + ");\n\n"
                + "abstract class RouteNames {}\n\n"
                + "class NavigationHelper { NavigationHelper._(); }\n";
    }
}
